"project_id_env": "CROWDIN_ZERO24_PROJECT_ID"
"api_token_env": "CROWDIN_ZERO24_PERSONAL_TOKEN"
"base_path": "language/"
"base_url": "https://joomla.crowdin.com"
"preserve_hierarchy": true
"files": [
  {
    "source": "/en-GB/en-GB.plg_contact_antispamextended.ini",
    "translation": "/%locale%/%locale%.plg_contact_antispamextended.ini",
    "update_option": "update_as_unapproved"
  },
  {
    "source": "/en-GB/en-GB.plg_contact_antispamextended.sys.ini",
    "translation": "/%locale%/%locale%.plg_contact_antispamextended.sys.ini",
    "update_option": "update_as_unapproved"
  }
]
